\contentsline {suppfigure}{\numberline {1}{\ignorespaces RNA-Seq data was obtained from BrainSpan.}}{36}{}%
\contentsline {suppfigure}{\numberline {2}{\ignorespaces Principal components analysis of transformed gene quantifications.}}{37}{}%
\contentsline {suppfigure}{\numberline {3}{\ignorespaces Principal components analysis of transformed isoform quantifications.}}{38}{}%
\contentsline {suppfigure}{\numberline {4}{\ignorespaces Relative log expression analysis of transformed gene quantifications.}}{39}{}%
\contentsline {suppfigure}{\numberline {5}{\ignorespaces Relative log expression analysis of transformed isoform quantifications.}}{40}{}%
\contentsline {suppfigure}{\numberline {6}{\ignorespaces Comparison of relative expression from qPCR and BrainSpan.}}{41}{}%
